apiVersion: skaffold/v2alpha3
kind: Config

build:
  local:
    useDockerCLI: true
    push: false
    concurrency: 0
  tagPolicy:
    sha256: {}
  artifacts:
    - image: pairfy/frontend-seller
      context: frontend-seller
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.{ts,js,json,vue}'
            dest: .
            
    - image: pairfy/service-seller
      context: service-seller
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.{ts,js,json,vue}'
            dest: .

    - image: pairfy/base-publisher
      context: base-publisher
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.{ts,js,json,vue}'
            dest: .

    - image: pairfy/base-consumer
      context: base-consumer
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.{ts,js,json,vue}'
            dest: .         

    - image: pairfy/service-email
      context: service-email
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.{ts,js,json,vue}'
            dest: .   

    - image: pairfy/service-product
      context: service-product
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.{ts,js,json,vue}'
            dest: .                

    - image: pairfy/service-llm
      context: service-llm
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.py'
            dest: .
          - src: 'requirements.txt'
            dest: .

    - image: pairfy/service-query
      context: service-query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.{ts,js,json,vue}'
            dest: .  

    - image: pairfy/service-product
      context: service-product
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.{ts,js,json,vue}'
            dest: .     

deploy:
  statusCheckDeadlineSeconds: 540
  kubectl:
    manifests:
      - ./A/k8s/*
      - ./A/k8s-dev/*

portForward:
  - resourceType: service
    resourceName: service-seller
    namespace: default
    port: 8000
    localPort: 8000

  - resourceType: service
    resourceName: service-product
    namespace: default
    port: 8001
    localPort: 8001    

  - resourceType: service
    resourceName: service-llm
    namespace: default
    port: 8002
    localPort: 8002

  - resourceType: service
    resourceName: service-media
    namespace: default
    port: 8003
    localPort: 8003 

  - resourceType: service
    resourceName: service-query
    namespace: default
    port: 8004
    localPort: 8004    

  - resourceType: service
    resourceName: weaviate
    namespace: default
    port: 8080
    localPort: 8080    

  - resourceType: service
    resourceName: ollama
    namespace: default 
    port: 11434
    localPort: 11434

  - resourceType: service
    resourceName: nats-ui-nui
    namespace: default 
    port: 31311
    localPort: 31311


