apiVersion: skaffold/v2alpha3
kind: Config

build:
  local:
    useDockerCLI: true
    push: false
    concurrency: 0
  tagPolicy:
    sha256: {}
  artifacts:
    - image: pairfy/frontend-seller
      context: frontend-seller
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.{ts,js,json,vue}'
            dest: .
    - image: pairfy/service-seller
      context: service-seller
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.{ts,js,json,vue}'
            dest: .


deploy:
  statusCheckDeadlineSeconds: 540
  kubectl:
    manifests:
      - ./A/k8s/*
      - ./A/k8s-dev/*

portForward:
  - resourceType: service
    resourceName: service-seller
    namespace: default
    port: 8000
    localPort: 8000
