global:
  enabled: true
  tlsDisable: true  # ✅ TLS 

server:
  enabled: true
  affinity: {}
  ha:
    enabled: true
    replicas: 1
    raft:
      enabled: true
      config: |
        ui = true

        listener "tcp" {
          address     = "0.0.0.0:8200"
          tls_disable = true
        }

        storage "raft" {
          path = "/vault/data"
        }

        service_registration "kubernetes" {}

  dataStorage:
    enabled: true
    size: 2Gi
    storageClass: standard

  readinessProbe:
    enabled: true

  resources:
    requests:
      memory: "512Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

injector:
  enabled: true

  metrics:
    enabled: true

  webhook:
    failurePolicy: Fail
