apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
data:
  master: xxx
  slave: xxx
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: streaming-config
data:
  redis: xxx
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cache-config
data:
  micro-store: redis://micro-store:6379
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rater-config
data:
  micro-store: redis://micro-store:6379
