apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-location
spec:
  replicas: 1
  selector:
    matchLabels:
      role: service-location
  template:
    metadata:
      labels:
        role: service-location
    spec:
      containers:
        - name: service-location
          image: pairfy/service-location
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name   
            - name: ENV_MODE
              value: 'prod'                                                               
            - name: POD_TIMEOUT
              value: '120000'   
            - name: EXPRESS_PORT
              value: "8000"
            - name: EXPRESS_TIMEOUT
              value: "30000"                                                                                                                                                 
            - name: CORS_DOMAINS
              value: "pairy.store"                           
            - name: DEV_IP
              value: "178.238.11.6" 
            - name: GEO_TOKEN
              value: "f76c9e2af54296"                 
          resources:
            limits:
              memory: "500Mi"
            requests:
              memory: "256Mi"       
---
apiVersion: v1
kind: Service
metadata:
  name: service-location
spec:
  selector:
    role: service-location
  ports:
    - name: service-location
      protocol: TCP
      port: 8000
      targetPort: 8000
