config:
  cluster:
    enabled: true
    replicas: 3
  jetstream:
    enabled: true
    fileStore:
      pvc:
        size: 50Gi
    streams:
    - name: product
      subjects: ["product.*"]  
      storage: file 
      retention: limits 
      maxMsgs: 1000  
      maxBytes: 1Gi  
      maxAge: 72h 
      replicas: 3 
    consumers:
    - name: service-gateway-consumer
      stream: product
      durableName: service-gateway-consumer
      deliverGroup: service-gateway-group
      ackPolicy: explicit 
      deliverPolicy: all 
      replayPolicy: instant
      maxAckPending: 100
      maxDeliver: -1
  monitor:
    enabled: true
    port: 8222
    tls:
      # config.nats.tls must be enabled also
      # when enabled, monitoring port will use HTTPS with the options from config.nats.tls
      enabled: false

podTemplate:
  topologySpreadConstraints:
    kubernetes.io/hostname:
      maxSkew: 1
      whenUnsatisfiable: DoNotSchedule

container:
  env:
    # different from k8s units, suffix must be B, KiB, MiB, GiB, or TiB
    # should be ~90% of memory limit
    GOMEMLIMIT: 12GiB
  merge:
    # recommended limit is at least 2 CPU cores and 8Gi Memory for production JetStream clusters
    resources:
      requests:
        cpu: "2"
        memory: 2Gi
      limits:
        cpu: "2"
        memory: 2Gi      

