name = "rey-sudo/marketplace"
version = "1.0.0"
compiler = "v1.1.0"
plutus = "v3"
description = "A next-level DeFi platform"

[repository]
user = "aiken-lang"
project = "stdlib"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2"
source = "github"

[config]
