persistence:
  enabled: true
  size: 10Gi         
  storageClass: ""   

config:
  storage: /verdaccio/storage
  uplinks:
    npmjs:
      url: https://registry.npmjs.org/
  packages:
    '@pairfy/common':
      access: $all
      publish: $authenticated
      proxy: false       
    '**':
      access: $all
      publish: $authenticated
      proxy: npmjs

server:
  listen: 0.0.0.0:4873

service:
  type: NodePort
