apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_USER
          value: marketplace
        - name: MYSQL_PASSWORD
          value: password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        - name: mysql-config
          mountPath: /etc/mysql/my.cnf
          subPath: my.cnf  
        - name: init-scripts
          mountPath: /docker-entrypoint-initdb.d/init.sql
          subPath: init.sql              
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: mysql-config
        configMap:
          name: mysql-config   
      - name: init-scripts
        configMap:
          name: init-scripts            
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  my.cnf: |
    [mysqld]
    bind-address = 0.0.0.0
    max_connections = 100000
    binlog_expire_logs_seconds = 604800
    thread_cache_size = 600
    innodb_buffer_pool_size = 10000000000
    innodb_log_buffer_size = 500000000
    innodb_flush_log_at_trx_commit = 2
    innodb_io_capacity = 4000
    tmp_table_size = 250000000
    max_heap_table_size = 250000000
    max_allowed_packet = 64000000
    net_buffer_length = 64000


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-scripts
data:
  init.sql: |
    GRANT ALL PRIVILEGES ON *.* TO 'marketplace'@'%';

    GRANT CREATE, ALTER, DROP, INDEX, CREATE TEMPORARY TABLES, LOCK TABLES, REFERENCES ON *.* TO 'marketplace'@'%';

    GRANT SELECT, RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'marketplace'@'%';

    ALTER USER 'marketplace'@'%' IDENTIFIED BY 'password';


    SELECT variable_value as "BINARY LOGGING STATUS (log-bin) ::"
    FROM performance_schema.global_variables WHERE variable_name='log_bin';


    FLUSH PRIVILEGES;

    CREATE DATABASE service_product;

    CREATE DATABASE service_gateway;
    
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-node
spec:
  type: LoadBalancer
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql

