replicaCount: 2

persistence:
  enabled: true
  storageClassName: "standard"
  size: 5Gi
  accessModes:
    - ReadWriteOnce

resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1Gi" 
    cpu: "1000m"

weaviate:
  modules:
    enabled: false
  config:
    persistence:
      enabled: true
    cluster:
      nodeCount: 2
    authentication:
      anonymousAccess:
        enabled: true
    replication:
      factor: 2 

service:
  type: LoadBalancer
  port: 8080

livenessProbe:
  httpGet:
    path: /v1/.well-known/ready
    port: 8080
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /v1/.well-known/ready
    port: 8080
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
