version: '3'
services:
  service-node:
    build:
      context: ./service-node
    volumes:
      - shared_volume:/app/node
    ports:
      - "3001:3001"
    mem_limit: 8Gib

  service-index:
    build:
      context: ./service-index
    volumes:
      - shared_volume:/app/node
    ports:
      - "9083:9083"
    mem_limit: 8Gib

  service-pab:
    build:
      context: ./plutus-example
    volumes:
      - shared_volume:/app/node
    ports:
      - "9080:9080"
    mem_limit: 8Gib

volumes:
  shared_volume:
