version: '3'
services:
  service-node:
    build:
      context: ./service-node
    volumes:
      - shared_volume:/app/node
    ports:
      - "9037:30"

  service-index:
    build:
      context: ./service-index
    volumes:
      - shared_volume:/app/node
    ports:
      - "9038:90"

volumes:
  shared_volume:
