version: '3'
services:
  service-node:
    build:
      context: ./service-node
    volumes:
      - shared_volume:/app/node
    ports:
      - "3001:3001"
    restart: always
    
  service-index:
    build:
      context: ./service-index
    volumes:
      - shared_volume:/app/node
    ports:
      - "9083:9083"
    depends_on:
      - service-node
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9083/healthcheck"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s          
    restart: always

  service-pab:
    build:
      context: ./plutus-example
    volumes:
      - shared_volume:/app/node
    ports:
      - "9080:9080"
    depends_on:
      - service-node
      - service-index
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9080/api/healthcheck"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s 
    restart: always


volumes:
  shared_volume:
