apiVersion: v1
kind: Pod
metadata:
  name: cockroachdb-client-secure
spec:
  serviceAccountName: database1-cockroachdb # Change to {release}
  containers:
  - name: cockroachdb-client-secure
    image: cockroachdb/cockroach:v23.1.13 # Change to cockroachdb/cockroach:{version}
    imagePullPolicy: IfNotPresent
    command:
    - sleep
    - "2147483648" # 2^31
  terminationGracePeriodSeconds: 0

        
