apiVersion: v1
kind: Secret
metadata:
  name: debezium-secret
  namespace: default
type: Opaque
data:
  username: bWFya2V0cGxhY2UK
  password: cGFzc3dvcmQK
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: connector-configuration-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["debezium-secret"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: connector-configuration-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: debezium-connect-cluster-connect
  namespace: default
roleRef:
  kind: Role
  name: connector-configuration-role
  apiGroup: rbac.authorization.k8s.io



