apiVersion: apps/v1
kind: Deployment
metadata:
  name: verba
  labels:
    app: verba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: verba
  template:
    metadata:
      labels:
        app: verba
    spec:
      containers:
        - name: verba
          image: semitechnologies/verba:latest
          ports:
            - containerPort: 8000
          env:
            - name: WEAVIATE_URL_VERBA
              value: http://localhost:8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: verba
spec:
  selector:
    app: verba
  ports:
    - protocol: TCP
      port: 7001
      targetPort: 8000
  type: ClusterIP
