apiVersion: apps/v1
kind: Deployment
metadata:
  name: debezium-connector
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debezium-connector
  template:
    metadata:
      labels:
        app: debezium-connector
    spec:
      containers:
      - name: debezium-connector
        image: debezium/connect
        env:
        - name: BOOTSTRAP_SERVERS
          value: "kafka-cluster-kafka-bootstrap:9092"
        - name: GROUP_ID
          value: "1"
        - name: CONFIG_STORAGE_TOPIC
          value: "kafka-cluster-configs"
        - name: OFFSET_STORAGE_TOPIC
          value: "kafka-cluster-offsets"
        - name: STATUS_STORAGE_TOPIC
          value: "kafka-cluster-status"
        - name: CONFIG_STORAGE_REPLICATION_FACTOR
          value: "3"
        - name: OFFSET_STORAGE_REPLICATION_FACTOR
          value: "3"
        - name: STATUS_STORAGE_REPLICATION_FACTOR
          value: "3"
        - name: OFFSET_FLUSH_INTERVAL_MS
          value: "60000"
        - name: DATABASE_HOSTNAME
          value: "10.96.222.125"
        - name: DATABASE_PORT
          value: "3306"
        - name: DATABASE_USER
          value: "user"
        - name: DATABASE_PASSWORD
          value: ""
        - name: DATABASE_SERVER_NAME
          value: "service-seller"
        - name: DATABASE_WHITELIST
          value: "service-seller"
        ports:
        - containerPort: 8083
