apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-media
spec:
  replicas: 1
  selector:
    matchLabels:
      role: service-media
  template:
    metadata:
      labels:
        role: service-media
    spec:
      containers:
        - name: service-media
          image: pairfy/service-media
          env:                                  
            - name: AGENT_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: agent-token-secret
                  key: AGENT_TOKEN_KEY                       
                                                        
            - name: DATABASE_HOST  
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: master   

            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: port  

            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-password-secret
                  key: password         

            - name: DATABASE_NAME
              value: service_media 
            - name: DATABASE_USER
              value: marketplace 
            - name : REDIS_RATELIMIT_URL
              value: "redis://redis-limiter:6379"                
            - name : MINIO_HOST_URL
              value: minio
            - name : MINIO_PORT
              value: "9000"
            - name : MINIO_USE_SSL
              value: "false"
            - name : MINIO_ACCESS_KEY
              value: "minioadmin"
            - name : MINIO_SECRET_KEY
              value: "minioadmin123"                            
          resources:
            limits:
              memory: "500Mi"
            requests:
              memory: "256Mi"       
---
apiVersion: v1
kind: Service
metadata:
  name: service-media
spec:
  selector:
    role: service-media
  ports:
    - name: service-media
      protocol: TCP
      port: 8003
      targetPort: 8003
