apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-state
spec:
  replicas: 1
  selector:
    matchLabels:
      role: service-state
  template:
    metadata:
      labels:
        role: service-state
    spec:
      containers:
        - name: service-state
          image: pairfy/service-state
          env:
            - name: DATABASE_NAME
              value: service_gateway       
            - name: DATABASE_USER
              value: marketplace 
            - name: REDIS_STATE_HOST
              value: redis://redis-state:6379
            - name: REDIS_BOOKS_HOST
              value: redis://redis-books:6379              
            - name: QUERY_LIMIT
              value: "1000"        
            - name: QUERY_INTERVAL
              value: "60000"       
            - name: SCAN_RANGE
              value: "300000"           
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DATABASE_HOST  
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: master  
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: port                                     
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-password-secret
                  key: password                       
            - name: PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: blockfrost-key
                  key: key        
            - name: KUPO_KEY
              valueFrom:
                secretKeyRef:
                  name: kupo-key
                  key: key 
            - name: OGMIOS_KEY
              valueFrom:
                secretKeyRef:
                  name: ogmios-key
                  key: key    

          resources:
            limits:
              memory: "500Mi"
            requests:
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: service-state
spec:
  selector:
    role: service-state
  ports:
    - name: service-state
      protocol: TCP
      port: 8008
      targetPort: 8008
