apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: service-gateway-consumer
spec:
  selector:
    matchLabels:
      role: service-gateway-consumer
  replicas: 3
  template:
    metadata:
      labels:
        role: service-gateway-consumer
    spec:
      containers:
        - name: service-gateway-consumer
          image: pairfy/base-consumer
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_TIMEOUT
              value: "120000"
            - name: DATABASE_USER
              value: marketplace
            - name: DATABASE_PASSWORD
              value: password
            - name: DATABASE_NAME
              value: service_gateway
            - name: STREAM_LIST
              value: product,query
            - name: SERVICE_NAME
              value: service-gateway
            - name: CONSUMER_GROUP
              value: service-gateway-group
            - name: DURABLE_NAME
              value: service-gateway-consumer
            - name: CONCURRENT_LIMIT
              value: "100"
          resources:
            limits:
              memory: "500Mi"
            requests:
              memory: "256Mi"
