apiVersion: v1
kind: PersistentVolume
metadata:
  name: service-index-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /index
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: service-index-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-index
spec:
  replicas: 1
  selector:
    matchLabels:
      role: service-index
  template:
    metadata:
      labels:
        role: service-index
    spec:
      containers:
        - name: service-index
          image: pairfy/service-index                       
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NETWORK
              value: preview                 
            - name: NETWORK_ID
              value: "2"         
            - name: CONFIG
              value: "/app/index/configuration/$(NETWORK)"
            - name: PATH
              value: "/app/index:${PATH}"                
            - name: SOCKET_PATH
              value: "/app/node/configuration/$(NETWORK)"                             
          resources:
            requests:
              memory: "556Mi"
          volumeMounts:
            - name: storage-volume 
              mountPath: /app/index
            - name: node-volume
              mountPath: /app/node                
      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: service-index-pvc
        - name: node-volume
          persistentVolumeClaim:
            claimName: service-node-pvc                     
---
apiVersion: v1
kind: Service
metadata:
  name: service-index
spec:
  selector:
    role: service-index
  ports:
    - name: service-index
      protocol: TCP
      port: 9083
      targetPort: 9083
