apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-seller
spec:
  replicas: 1
  selector:
    matchLabels:
      role: service-seller
  template:
    metadata:
      labels:
        role: service-seller
    spec:
      containers:
        - name: service-seller
          image: pairfy/service-seller
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_TIMEOUT
              value: '120000'                                                       
            - name: EVENT_BUS_URI
              valueFrom:
                configMapKeyRef:
                  name: streaming-config
                  key: redis                                                
            - name: USERS_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY                  
            - name: ADMIN_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: admin-jwt-secret
                  key: ADMIN_JWT_KEY   
            - name: GENERAL_LIMIT_TIME
              value: "9000"     
            - name: GENERAL_LIMIT_MAX
              value: "15000"
            - name: CRITICAL_LIMIT_TIME
              value: "86400" 
            - name: CRITICAL_LIMIT_MAX
              value: "2000"                                                                     
            - name: TOKEN_EXPIRATION_TIME
              value: 2h
            - name: EXPRESS_PORT
              value: "8000"
            - name: EXPRESS_TIMEOUT
              value: "180000"
            - name: PUBLISHER_ROLE
              value: "publisher-store"
            - name: CORS_DOMAINS
              value: "https://pairfy.dev,http://pairfy.dev,http://localhost:8080"                           
          resources:
            limits:
              memory: "500Mi"
            requests:
              memory: "256Mi"       
---
apiVersion: v1
kind: Service
metadata:
  name: service-seller
spec:
  selector:
    role: service-seller
  ports:
    - name: service-seller
      protocol: TCP
      port: 8000
      targetPort: 8000
