apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      role: service-gateway
  template:
    metadata:
      labels:
        role: service-gateway
    spec:
      containers:
        - name: service-gateway
          image: pairfy/service-gateway
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name                                       
            - name: SELLER_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: seller-token-secret
                  key: SELLER_TOKEN_KEY    
            - name: USER_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: user-token-secret
                  key: USER_TOKEN_KEY                                       
            - name: POD_TIMEOUT
              value: '120000'   
            - name: EXPRESS_PORT
              value: "8000"
            - name: EXPRESS_TIMEOUT
              value: "30000"                                                                  
            - name: REDIS_URI  
              value: redis://service-gateway-redis:6379                                                                                  
            - name: TOKEN_EXPIRATION
              value: "7d"
            - name: CORS_DOMAINS
              value: "https://pairfy.dev,http://pairfy.dev,http://localhost:8080,http://localhost:8081,https://pairfy.dev,https://dashboard.pairfy.dev"                           
          resources:
            limits:
              memory: "500Mi"
            requests:
              memory: "256Mi"       
---
apiVersion: v1
kind: Service
metadata:
  name: service-gateway
spec:
  selector:
    role: service-gateway
  ports:
    - name: service-gateway
      protocol: TCP
      port: 8000
      targetPort: 8000
