---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: llama-models-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /mnt/models 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-models-pvc
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
  volumeName: llama-models-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-llm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-llm
  template:
    metadata:
      labels:
        app: service-llm
    spec:
      containers:
        - name: service-llm
          image: pairfy/service-llm
          ports:
            - containerPort: 8000
          env:
            - name: MODEL_PATH
              value: /models/DeepSeek-R1-Distill-Qwen-14B-Q4_K_M.gguf
          volumeMounts:
            - name: gguf-models
              mountPath: /models
              readOnly: true
      volumes:
        - name: gguf-models
          persistentVolumeClaim:
            claimName: llama-models-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: service-llm
spec:
  selector:
    app: service-llm
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
