apiVersion: v1
kind: Service
metadata:
  name: service-processor-redis
  namespace: default
  labels:
    app: service-processor-redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: service-processor-redis

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: service-processor-redis
  namespace: default
  labels:
    app: service-processor-redis
spec:
  serviceName: "service-processor-redis"
  replicas: 1
  selector:
    matchLabels:
      app: service-processor-redis
  template:
    metadata:
      labels:
        app: service-processor-redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: service-processor-redis-data
              mountPath: /data
          command: ["redis-server", "--appendonly", "yes"]
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: service-processor-redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests:
            storage: 500Mi
