apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: service-query-consumer
spec:
  selector:
    matchLabels:
      role: service-query-consumer
  replicas: 1
  template:
    metadata:
      labels:
        role: service-query-consumer
    spec:
      containers:
        - name: service-query-consumer
          image: pairfy/base-consumer
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name                                                             
            - name: POD_TIMEOUT
              value: '120000'   
            - name: DATABASE_USER
              value: marketplace
            - name: DATABASE_PASSWORD
              value: password
            - name: DATABASE_NAME
              value: service_product                                                                                                                                                               
            - name: STREAM_LIST
              value: product           
            - name: SERVICE_NAME
              value: service-query 
            - name: CONSUMER_GROUP
              value: service-query-group                                  
          resources:
            limits:
              memory: "500Mi"
            requests:
              memory: "256Mi"       
