apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-product-publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      role: service-product-publisher
  template:
    metadata:
      labels:
        role: service-product-publisher
    spec:
      containers:
        - name: service-product-publisher
          image: pairfy/base-publisher
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name                                       
            - name: SELLER_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: seller-token-secret
                  key: SELLER_TOKEN_KEY                       
            - name: POD_TIMEOUT
              value: '120000'   
            - name: EXPRESS_PORT
              value: "8000"
            - name: EXPRESS_TIMEOUT
              value: "120000"                                                                  
            - name: BUS_STREAMING_URI  
              valueFrom:
                configMapKeyRef:
                  name: streaming-config
                  key: redis                                                                                  
            - name: TOKEN_EXPIRATION
              value: "7d"
            - name: CORS_DOMAINS
              value: "http://localhost:5173,http://localhost:8080,http://localhost:8081,http://localhost:443,localhost,https://pairfy.dev,https://dashboard.pairfy.dev"                          
          resources:
            limits:
              memory: "500Mi"
            requests:
              memory: "256Mi"       
