apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: service-gate-stream
  labels:
    strimzi.io/cluster: debezium-connect-cluster
spec:
  class: io.debezium.connector.mysql.MySqlConnector
  tasksMax: 1
  config:
    name: service-gate-stream
    connector.class: io.debezium.connector.mysql.MySqlConnector
    database.hostname: "mysql"
    database.port: 3306
    database.user: "marketplace"
    database.password: "password"
    database.server.id: "50002"
    database.include.list: "service_gate"
    topic.prefix: "fullfillment"
    schema.history.internal.kafka.bootstrap.servers: "streaming-kafka-bootstrap:9092,streaming-kafka-bootstrap:9092,streaming-kafka-bootstrap:9092"
    schema.history.internal.kafka.topic: "schemahistory.fullfillment"
    include.schema.changes": "true"
    snapshot.mode: "when_needed"
