apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: service-seller-stream
  labels:
    strimzi.io/cluster: debezium-connect-cluster
spec:
  class: io.debezium.connector.vitess.VitessConnector
  tasksMax: 1
  config:
    connector.class: io.debezium.connector.vitess.VitessConnector
    database.hostname: "10.101.74.192"
    database.port: "3306"
    database.user: "marketplace"
    database.password: "password" 
    topic.prefix: "fullfillment"
    vitess.keyspace: "service_seller"
    vitess.tablet.type: "MASTER"
    vitess.vtctld.host": "10.101.74.192"
    vitess.vtctld.port": "3306"
    vitess.vtctld.user": "marketplace"
    vitess.vtctld.password: "password"  
    vitess.database.user: "marketplace"
    vitess.database.password: "password"
    database.server.id: 184054
    topic.naming.strategy: "topico"
    database.include.list: service_seller
    schema.history.internal.kafka.bootstrap.servers: streaming-kafka-bootstrap:9092,streaming-kafka-bootstrap:9092,streaming-kafka-bootstrap:9092
    schema.history.internal.kafka.topic: schema-changes.service_seller
    table.include.list: "seller"   
    name: debezium-connector-vitess
    tasks.max: 1 