apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-query
spec:
  replicas: 1
  selector:
    matchLabels:
      role: service-query
  template:
    metadata:
      labels:
        role: service-query
    spec:
      containers:
        - name: service-query
          image: pairfy/service-query
          env:
            - name: NODE_ENV
              value: development                                          
            - name: DATABASE_HOST  
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: master  
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: port                                     
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-password-secret
                  key: password                                  
            - name: DATABASE_NAME
              value: service_query       
            - name: DATABASE_USER
              value: marketplace    
            - name: SERVICE_STATE_REDIS
              value: redis://service-state-redis:6379    
            - name : REDIS_RATELIMIT_URL
              value: "redis://redis-limiter:6379"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name       
            - name: AGENT_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: agent-token-secret
                  key: AGENT_TOKEN_KEY 
            - name: WEAVIATE_HOST
              valueFrom:
                configMapKeyRef:
                  name: weaviate-config
                  key: host 
            - name: EMBEDDING_HOST
              valueFrom:
                configMapKeyRef:
                  name: embedding-config
                  key: host                                                                                                                                                                                                                                                         
          resources:
            limits:
              memory: "500Mi"
            requests:
              memory: "256Mi"       
---
apiVersion: v1
kind: Service
metadata:
  name: service-query
spec:
  selector:
    role: service-query
  ports:
    - name: service-query
      protocol: TCP
      port: 8004
      targetPort: 8004
