apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-product
spec:
  replicas: 1
  selector:
    matchLabels:
      role: service-product
  template:
    metadata:
      labels:
        role: service-product
    spec:
      containers:
        - name: service-product
          image: pairfy/service-product
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name   
            - name: ADMIN_SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: admin-session-secret
                  key: key                                                      
            - name: AGENT_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: agent-token-secret
                  key: AGENT_TOKEN_KEY                      
            - name: DATABASE_HOST  
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: master  
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: port                                     
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-password-secret
                  key: password   
            - name: DATABASE_NAME
              value: service_product        
            - name: DATABASE_USER
              value: marketplace  
            - name : REDIS_RATELIMIT_URL
              value: "redis://redis-limiter:6379"
                                                                                                                                                                                                     
          resources:
            limits:
              memory: "500Mi"
            requests:
              memory: "256Mi"       
---
apiVersion: v1
kind: Service
metadata:
  name: service-product
spec:
  selector:
    role: service-product
  ports:
    - name: service-product
      protocol: TCP
      port: 8001
      targetPort: 8001
