apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: service-state-redis-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard

---

apiVersion: v1
kind: Service
metadata:
  name: service-state-redis
  namespace: default
  labels:
    app: service-state-redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: service-state-redis

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: service-state-redis
  namespace: default
spec:
  serviceName: "service-state-redis"
  replicas: 1
  selector:
    matchLabels:
      app: service-state-redis
  template:
    metadata:
      labels:
        app: service-state-redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: service-state-redis-data
              mountPath: /data
          command: [ "redis-server", "--appendonly", "yes" ]
  volumeClaimTemplates:
    - metadata:
        name: service-state-redis-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: standard
        resources:
          requests:
            storage: 500Mi
