name: frontend-main

on:
  push:
    branches:
      - main
    paths:
      - 'frontend-main/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.MARKETPLACE_DOCKER_USER }}
          password: ${{ secrets.MARKETPLACE_DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t pairfy/frontend-main ./frontend-main

      - name: Push Docker image
        run: docker push pairfy/frontend-main

      - name: Set up DigitalOcean CLI
        uses: digitalocean/action-doctl@v3
        with:
          token: ${{ secrets.MARKETPLACE_CLOUD_API }}

      - name: Set up kubeconfig
        run: doctl kubernetes cluster kubeconfig save do-nyc3-marketplace-k8

      - name: Restart Kubernetes deployment
        run: kubectl rollout restart deployment frontend-main
