name: deploy-kubemanifest

on:
  push:
    branches:
      - main
    paths:
      - 'A/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.MARKETPLACE_CLOUD_API }}
      - run: doctl kubernetes cluster kubeconfig save do-nyc3-marketplace-k8
      - run: kubectl apply -f A/k8s-prod
      